[project]
name = "plaincv"
version = "0.1.0"
requires-python = ">=3.10"

dependencies = [
  "jax",                 # or jax[cuda12_pip] depending on your setup
  "flax",
  "optax",
  "tensorflow-datasets",
  "ml-collections",      # if you want Flax-style config dicts later
  "tqdm",
]
